### ISSUE TITLE
Make containers autocompact by default

### ISSUE THREAD

**Issue by ecto** [SpiderOak/crypton#308]
Requires https://github.com/SpiderOak/crypton/issues/307. This would make container loading faster by default while still allowing the possibility to have historical data.

**Comment by daviddahl** [comment]
How much work is this? What has to be done? What is the simplest solution we can implement quickly that is not shite?

**Comment by daviddahl** [comment]
Fixed in finish-items branch, we have a new data type instead of trying to fix containers.
