### ISSUE TITLE
Change Crypton client code license to MPL 2

### ISSUE THREAD

**Issue by daviddahl** [SpiderOak/crypton#368]
http://choosealicense.com/licenses/apache-2.0/
Literally no one but us can submit to the iOS app store, and, anything GPL is toxic in iOS-land, so we need to do this now.

Talked to @devgeeks and we think Apache is the best choice.

**Comment by daviddahl** [comment]
@alanfairless I know you signed off on this on the past, with your +1 I will begin to change the headers and create a new LICENSE file inside client/

**Comment by daviddahl** [comment]
I think we will need +1s from @kainz @bytex64 @dhain @sporgj & @ecto as well

My view is +1

**Comment by daviddahl** [comment]
We need this for Kloak and Encryptr to get them into the App Store. Also, the license for client code should have always been something other than *GPL*:)

**Comment by devgeeks** [comment]
reference:

https://www.fsf.org/news/2010-05-app-store-compliance

https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-1.rg/blogs/licensing/more-about-the-app-store-gpl-enforcement

**Comment by kainz** [comment]
+1

**Comment by devgeeks** [comment]
+1

**Comment by daviddahl** [comment]
See PR #373

**Comment by daviddahl** [comment]
fixed in PR 373
