### ISSUE TITLE
Unhandled Exception thrown by pg.native in server account test

### ISSUE THREAD

**Issue by tr3ddy** [SpiderOak/crypton#371]
I tried to run crypton on Ubuntu with Postgres 9.4.3. Everytime the test for Postgres driver fails:

 Postgres driver
    Account
      saveAccount
        ✓ inserts rows for account and keyring
        ◦ returns an error if username is taken: Unhandled database error: Error: ERROR:  duplicate key value violates unique constraint "account_username_key"
DETAIL:  Key (username)=(testuser) already exists.

uncaught exception: { [AssertionError: 'Database error.' == 'Username already taken.']
  name: 'AssertionError',
  actual: 'Database error.',
  expected: 'Username already taken.',
  operator: '==',
  message: '\'Database error.\' == \'Username already taken.\'',
  generatedMessage: true } AssertionError: 'Database error.' == 'Username already taken.'
    at /home/treddy/crypton/server/test/stores/postgres/account.js:80:18
    at null.callback (/home/treddy/crypton/server/lib/stores/postgres/account.js:82:11)
    at NativeQuery.handleError (/home/treddy/crypton/server/node_modules/pg/lib/native/query.js:39:10)
    at after (/home/treddy/crypton/server/node_modules/pg/lib/native/query.js:59:19)
    at onError (/home/treddy/crypton/server/node_modules/pg-native/index.js:160:5)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at Client._readError (/home/treddy/crypton/server/node_modules/pg-native/index.js:81:8)
    at Client._read (/home/treddy/crypton/server/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)
Makefile:4: recipe for target 'test-unit' failed
make[1]: *** [test-unit] Error 1
Makefile:8: recipe for target 'test-unit-server' failed
make: *** [test-unit-server] Error 2

When going back from pg.native to pg, all tests work fine.

**Comment by tomymolina** [comment]
I have the same issue with postgresql version 9.3.9.

**Comment by daviddahl** [comment]
I will be able to look into this sometime in the next week. Sorry for the delay

**Comment by daviddahl** [comment]
A quick look makes me think the driver is handing back a string we don't expect in the error argument to the callback. this is an easy test fix, we just need to expect either error in the test.

**Comment by daviddahl** [comment]
Sigh, looks like this is related to https://github.com/brianc/node-postgres/issues/746

**Comment by daviddahl** [comment]
I think a good fix for this is to write a query that checks for the account before inserting it blind, here:: https://github.com/SpiderOak/crypton/blob/master/server/lib/stores/postgres/account.js#L63

**Comment by ecto** [comment]
Looks like something changed upstream. Need to change this line. https://github.com/SpiderOak/crypton/blob/master/server/lib/stores/postgres/account.js#L78

**Comment by daviddahl** [comment]
fixed this issue here: https://github.com/SpiderOak/crypton/commit/294ac870fbad724b9065dcc9913616f829cf0409

**Comment by daviddahl** [comment]
@ecto that's what I thought too, but what is actually happening is that an unhandled exception is thrown instead of the error being passed to our connect callback - this is a difference in the native postgres driver. A bunch of folks discussed this in brianc/node-postgres#746

**Comment by ecto** [comment]
might be worth locking down to a version of `pg` that didn't have this problem and only change the one line

but i didn't know you were deprecating containers so maybe this way is better :stuck_out_tongue:

**Comment by daviddahl** [comment]
The containers code needs a lot of work, with a simpler API like Items, everything is faster and we don't have to do any diffing, etc. The history and timeline APIs are slowly being built out to handle versioning, etc. We are offloading the hard work to Postgresql instead of dealing with diffs, etc locally.

**Comment by daviddahl** [comment]
fixed in #375
