### ISSUE TITLE
Content Security Policy (CSP) Allow blob: data sources

### ISSUE THREAD

**Issue by grempe** [SpiderOak/crypton#386]
In at least Chrome (46) there is a browser Content Security Policy violation error on loading the examples from the server.  This is due to ‘blob:’ being used in the code but not defined as an acceptable data source.

Example console output:

````
Refused to create a child context containing 'blob:https%3A//localhost%3A1025/e86679df-de28-4a77-a7db-0029597ff71f' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'child-src' was not explicitly set, so 'default-src' is used as a fallback.
#    crypton.js:6291
````

````
Uncaught SecurityError: Failed to construct 'Worker': Access to the script at 'blob:https%3A//localhost%3A1025/e86679df-de28-4a77-a7db-0029597ff71f' is denied by the document's Content Security Policy.
#    crypton.js:6291
````

Specifying blob: as an allowed data source in a content security policy is documented here:
https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Data

**Comment by daviddahl** [comment]
FIxed in #387
