### ISSUE TITLE
make: *** [test-unit] Error 1 - Server Build Fail

### ISSUE THREAD

**Issue by 4oo4** [SpiderOak/crypton#429]
Attempting to install on Ubuntu 14.04.3, and I'm getting stuck when I do `make test` for the server, though I get no errors when building the client nor running the dependencies script. The only error message I get is: `make: *** [test-unit] Error 1`, and haven't found anything useful in the npm -debug.log

I have been following the installation guide precisely and am not sure where I went wrong. Is there something I'm missing?
###### Edit:

Please close; I'm not sure what I did but it's now building correctly. I think it was an issue of nvm vs. a system install of nodejs

**Comment by daviddahl** [comment]
Ubunti 14 might be a bit old. Does the server run?

**Comment by daviddahl** [comment]
try to ping me on irc - i am "ddahl"

**Comment by daviddahl** [comment]
I just fixed some version strings in tests on master and have tested everything on Ubuntu 15.04

**Comment by 4oo4** [comment]
@daviddahl Sorry to leave this open for so long, I was eventually able to get this fixed by redoing the build from scratch, both on 14 as well as when I migrated it to 16.
