### ISSUE TITLE
sharing/unsharing containers and access to history

### ISSUE THREAD

**Issue by dgreisen** [SpiderOak/crypton#430]
Hello. Thanks for the great project.

My use-case requires that a user be able to share/unshare a container with a peer an arbitrary number of times. A peer needs access to the history of data for all time periods when that data was shared with the peer, but not for periods when it was not shared. At first I thought I couldn't do this with crypton, but I think I've figure a way to do it in "user space" without modifying the guts of crypton. I create a new container each time I add or remove a user. Each container name would look something like `<id>-<rev>`, where rev is an incrementing number.

I can minimize container creation when a peer is:
* removed by flagging the container as `"dirty": true`, and then lazily creating a new container the next time the container's contents is modified. 
* added by not creating a new container when the existing container has never been modified - the container has not been changed since the last person was added/removed, so don't need to re-encrypt. 

I could thus add and remove an arbitrary number of peers between modifications of container content while only creating, at most, a single new container. The worst-case scenario would be alternating adding/removing a peer and modifying the content, leading to a new container every time a peer was added/removed.

If this seems like a reasonable way forward, and something that others might find useful, I'd be happy to take a stab at creating a new container type and making a pr.

Thank you for your time.

**Comment by dgreisen** [comment]
After digging through the code, it looks like containers are deprecated. I'm implementing on top of the Item api as instructed.

**Comment by daviddahl** [comment]
Sorry for the delay, just seeing this issue now. Containers were a clever idea, but the massive problem with them is when you load a well-used container the performance is really really terrible. Items API is an attempt to do things simply. The history API can give you historical changes.

**Comment by dgreisen** [comment]
Thanks for the info. Does the history implementation ensure that if an item is shared with a peer, then unshared, then shared again, the peer only has access to the history items from when the item was actively being shared? Thanks.
