### ISSUE TITLE
development stalled?

### ISSUE THREAD

**Issue by petervnv** [SpiderOak/crypton#449]
Hi all,

Is Crypton still being actively developed?
I see that PR 448 is still waiting to be committed so it can play nice with the recently committed changes in encryptr's code that now allow offline, exporting, etc

Is there any plan to commit https://github.com/SpiderOak/crypton/pull/448 ?

Cheers,
Peter

**Comment by petervnv** [comment]
Anyone?
It seems PR 448 is still in limbo although the corresponding PRs on encryptr have already been merged https://github.com/SpiderOak/Encryptr/issues/286

**Comment by BallisticPain** [comment]
I too am interested in whether or not Crypton is being maintained. I would love to leverage the expertise of SpiderOak to build some platforms from. However, I don't have the expertise to maintain this project myself. :-D

**Comment by devgeeks** [comment]
AFAIK, Crypton is _not_ being maintained. Any development would only be for features immediately required by Encryptr.

**Comment by petervnv** [comment]
Thanks @devgeeks 

But the current version of Encryptr on github (not released yet but compilable) already has new features like offline viewing/storage that need the corresponding patch on Crypton side no?

**Comment by rugk** [comment]
Website is down, too.

**Comment by merickson** [comment]
Hello everyone,

Wading in here from SpiderOak. Crypton is only here for historical purposes only, being effectively version 0 of the backend used for Semaphor (https://spideroak.com/semaphor/). The ability to build software on top of the backend being worked on for Semaphor 2 will be released as a product later this year.

Thank you everyone!
